AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Sample SAM Template for kpl-lambda"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:
  KPLProducerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: KPLProducer
      Handler: kplproducer.KPLProducer::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          KINESIS_STREAM_NAME: "sample-kpl-stream"
          REGION: "us-east-1"
          WOEID: "1"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KPLProducerFunction:
    Description: "KPL Producer Lambda Function ARN"
    Value: !GetAtt KPLProducerFunction.Arn
  KPLProducerFunctionRole:
    Description: "Implicit IAM Role created for KPL Producer function"
    Value: !GetAtt KPLProducerFuncionRole.Arn
